name: WakaTime Stats Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update WakaTime Stats
        run: |
          curl -o waka_stats.md https://github-readme-stats.vercel.app/api/wakatime?username=@yidnekachewtefera
          cat waka_stats.md >> README.md
      - name: Commit Changes
        run: |
          git config --local yomaytec@gmail.com "github-actions[bot]@users.noreply.github.com"
          git config --local yidnekachewtefera "github-actions[bot]"
          git add README.md
          git commit -m "Update WakaTime stats"
          git push
